import { Product } from './types';

export const products: Product[] = [
  {
    id: 'nc-1',
    name: 'Ayurvedic Radiance Night Cream',
    category: 'Night Creams',
    price: 299,
    originalPrice: 499,
    description: 'An ancient Ayurvedic formulation. This luxurious night cream repairs pigmentation, evens skin tone, and restores a youthful glow while you sleep.',
    benefits: ['Brightens skin tone', 'Reduces pigmentation and dark spots', 'Deeply hydrates and repairs overnight'],
    images: ['/night-cream.PNG'],
    variants: [{ name: 'Size', options: ['50g'] }],
    inStock: true,
    rating: 4.8,
    reviewsCount: 124,
    isFeatured: true,
  },
  {
    id: 'b-1',
    name: 'Classic Golden Bangles',
    category: 'Bangles',
    price: 199,
    originalPrice: 399,
    description: 'Elegant golden bangles perfect for festive occasions and daily wear. Crafted with precision for a timeless look.',
    benefits: ['Premium gold finish', 'Durable and lightweight', 'Classic design'],
    images: ['/Golden-Bangles.PNG'],
    variants: [{ name: 'Size', options: ['2.2', '2.4', '2.6', '2.8'] }],
    inStock: true,
    rating: 4.8,
    reviewsCount: 124,
    isFeatured: true,
  },
  {
    id: 'b-2',
    name: 'Golden Bangles Bal Design',
    category: 'Bangles',
    price: 249,
    originalPrice: 499,
    description: 'Beautiful golden bangles featuring a traditional Bal design. A stunning addition to any ethnic ensemble.',
    benefits: ['Intricate traditional pattern', 'High-quality plating', 'Comfortable fit'],
    images: ['/Golden-Bangles-Bal.PNG'],
    variants: [{ name: 'Size', options: ['2.2', '2.4', '2.6', '2.8'] }],
    inStock: true,
    rating: 4.9,
    reviewsCount: 89,
    isFeatured: true,
  },
  {
    id: 'b-3',
    name: 'Golden Designer Bangles',
    category: 'Bangles',
    price: 199,
    originalPrice: 399,
    description: 'Designer golden bangles with unique geometric patterns. Stand out from the crowd with this modern take on traditional jewelry.',
    benefits: ['Modern designer aesthetic', 'Tarnish-resistant', 'Statement piece'],
    images: ['/Golden-Desing-Bangles.PNG'],
    variants: [{ name: 'Size', options: ['2.2', '2.4', '2.6', '2.8'] }],
    inStock: true,
    rating: 4.7,
    reviewsCount: 56,
  },
  {
    id: 'b-4',
    name: 'Golden Kangan Multi-Color',
    category: 'Bangles',
    price: 299,
    originalPrice: 599,
    description: 'Exquisite golden Kangans adorned with vibrant multi-colored stones. Perfect for weddings and grand celebrations.',
    benefits: ['Rich multi-color stones', 'Heavy bridal look', 'Premium craftsmanship'],
    images: ['/Golden-Kangan-Multi-Color.PNG'],
    variants: [{ name: 'Size', options: ['2.2', '2.4', '2.6', '2.8'] }],
    inStock: true,
    rating: 4.9,
    reviewsCount: 210,
    isFeatured: true,
  },
  {
    id: 'b-5',
    name: 'Vibrant Multicolor Bangle',
    category: 'Bangles',
    price: 249,
    originalPrice: 499,
    description: 'A beautiful single bangle featuring a burst of vibrant colors. Mix and match with your favorite outfits.',
    benefits: ['Colorful versatile design', 'Lightweight for daily wear', 'Skin-friendly materials'],
    images: ['/Multicolor-Bangle.PNG'],
    variants: [{ name: 'Size', options: ['2.2', '2.4', '2.6', '2.8'] }],
    inStock: true,
    rating: 4.6,
    reviewsCount: 45,
  },
  {
    id: 'b-6',
    name: 'Silver Kangan Set',
    category: 'Bangles',
    price: 299,
    originalPrice: 599,
    description: 'Premium silver-plated Kangans with delicate traditional motifs. Brings a cool, elegant touch to your jewelry collection.',
    benefits: ['High-quality silver plating', 'Oxidised finish look', 'Sturdy and durable'],
    images: ['/Silver-Bangle-Kangan.PNG'],
    variants: [{ name: 'Size', options: ['2.2', '2.4', '2.6', '2.8'] }],
    inStock: true,
    rating: 4.8,
    reviewsCount: 132,
    isFeatured: true,
  },
  {
    id: 'b-7',
    name: 'Classic Silver Bangles',
    category: 'Bangles',
    price: 249,
    originalPrice: 499,
    description: 'A set of sleek and classic silver bangles. Understated elegance for everyday wear or office ethnic outfits.',
    benefits: ['Minimalist classic design', 'Anti-tarnish coating', 'Perfect for stacking'],
    images: ['/Silver-Bangles.PNG'],
    variants: [{ name: 'Size', options: ['2.2', '2.4', '2.6', '2.8'] }],
    inStock: true,
    rating: 4.7,
    reviewsCount: 78,
  }
];
